spring.profiles.active: local

spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: test

---

spring.config.activate.on-profile: prod

spring:
  r2dbc:
    url:
    username:
    password:
