name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04-arm

    env:
      IMAGE_TAG: ${{ github.run_number }}
      OCIR_REGISTRY: yny.ocir.io
      OCIR_NAMESPACE: ax1dvc8vmenm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to OCIR
        run: echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login $OCIR_REGISTRY -u $OCIR_NAMESPACE/members/waffle-deployer --password-stdin

      - name: Docker build, tag, and push image to OCIR
        run: |
          docker build \
            -f Dockerfile-consumer \
            -t $OCIR_REGISTRY/$OCIR_NAMESPACE/truffle-prod/truffle-consumer:$IMAGE_TAG \
            . \
            --platform linux/arm64
          docker push $OCIR_REGISTRY/$OCIR_NAMESPACE/truffle-prod/truffle-consumer:$IMAGE_TAG

          docker build \
            -f Dockerfile-dashboard \
            -t $OCIR_REGISTRY/$OCIR_NAMESPACE/truffle-prod/truffle-dashboard:$IMAGE_TAG \
            . \
            --platform linux/arm64
          docker push $OCIR_REGISTRY/$OCIR_NAMESPACE/truffle-prod/truffle-dashboard:$IMAGE_TAG

      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: project-truffle
          SLACK_TITLE: NEW RELEASE
          SLACK_USERNAME: truffle
          SLACK_ICON: https://user-images.githubusercontent.com/35535636/103177470-2237cb00-48be-11eb-9211-3ffa567c8ac3.png
          SLACK_MESSAGE: Check <https://argocd.wafflestudio.com|Argo CD> for updated environment